import time
time.sleep(30)
antwort = input("Wie alt bist du? ")
time.sleep(30)
antwort = input("Was ist deine LIeblingsfarbe? ")
time.sleep(30)
antwort = input("Was ist dein LIeblingstier? ")
time.sleep(30)
antwort = input("Liest du gerne Bücher? ")
time.sleep(30)
antwort = input("Hast du Geschwister? ")
time.sleep(30)
antwort = input("Hast du ein Haustier? ")
time.sleep(30)
antwort = input("Spielst du Videospiele? ")
time.sleep(30)
antwort = input("Treibst du Sport? ")
time.sleep(30)
antwort = input("Magst du Horrorfilme? ")
time.sleep(30)
antwort = input("Findest du sommer oder winter besser? ")
